// GENERATED by assets-pipeline/scripts/logo/extract_mark_geometry.py
// from public/brand/yuei-mark.svg — do not edit by hand.

export type Point = readonly [number, number];

export type MarkPiece = {
  /** Clip polygon in viewBox space. */
  points: readonly Point[];
  /** Gradient vector in viewBox space, from the light (sky) end to the dark (navy) end. */
  gradient: { x1: number; y1: number; x2: number; y2: number };
};

export type PillarFace = { name: "left" | "right" | "top"; points: readonly Point[] };

export const MARK_VIEWBOX = { x: 0.0, y: 0.0, width: 148.638, height: 172.6681 } as const;

/** The six flying pieces, in document order (left chain bottom->top, then right chain bottom->top). */
export const MARK_PIECES: readonly MarkPiece[] = [
  { points: [[40.667, 93.706], [45.062, 62.604], [69.782, 55.426], [66.986, 85.733]], gradient: {x1: 69.793, y1: 74.359, x2: 40.656, y2: 74.376} },
  { points: [[39.471, 61.012], [39.471, 32.298], [14.752, 41.469], [17.544, 64.200]], gradient: {x1: 14.72, y1: 49.694, x2: 39.514, y2: 49.79} },
  { points: [[0.000, 20.736], [2.790, 0.799], [19.941, 0.000], [15.952, 26.715]], gradient: {x1: 20.037, y1: 11.979, x2: -0.069, y2: 12.141} },
  { points: [[78.359, 75.163], [82.845, 53.034], [107.661, 61.708], [98.392, 81.747]], gradient: {x1: 95.103, y1: 56.597, x2: 88.619, y2: 78.906} },
  { points: [[101.984, 52.136], [96.298, 26.415], [113.645, 25.519], [118.429, 44.060]], gradient: {x1: 107.504, y1: 25.565, x2: 107.701, y2: 52.093} },
  { points: [[124.115, 27.313], [130.695, 6.978], [148.638, 18.639], [140.858, 35.987]], gradient: {x1: 139.781, y1: 9.655, x2: 132.729, y2: 33.592} },
];

export const PILLAR_FACES: readonly PillarFace[] = [
  { name: "left", points: [[71.972, 172.668], [50.437, 164.688], [50.437, 97.498], [71.972, 105.478]] },
  { name: "right", points: [[71.972, 172.668], [93.512, 164.688], [93.512, 97.498], [71.972, 105.478]] },
  { name: "top", points: [[72.106, 105.543], [50.422, 97.563], [71.919, 91.163], [93.608, 97.455]] },
];
